appurl=https://tutorialsninja.com/demo/
email=rajbele500@gmail.com
pwd=Rajbele@321321
execution_env=local
#execution_env=remote

#<class name="testCases.TC_001_AccountRegistrationTest"/>
    # <class name="testCases.TC_002_LoginTest"/>



 #http://10.157.68.246:4444